# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oslatlong < Formula
  desc "OSM Nominatim skinny CLI"
  homepage "https://github.com/oogali/oslatlong"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.1/oslatlong_0.0.1_Darwin_arm64.tar.gz"
      sha256 "deb2782048c15fd326d447d5b44fd456fa1f41a3d04d0c4ed8a496b88b1d3d47"

      def install
        bin.install "oslatlong"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.1/oslatlong_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "adc9900071975dc1f252602b2480bc8891203a3f761acb1a1bba14da1769fd7a"

      def install
        bin.install "oslatlong"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.1/oslatlong_0.0.1_Linux_armv6.tar.gz"
      sha256 "7026cffef8660991f47c246ae051a9929daf8779dab6ec18324e2cf0dd51b3c9"

      def install
        bin.install "oslatlong"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.1/oslatlong_0.0.1_Linux_arm64.tar.gz"
      sha256 "f0e5a38b149dc682214a76462ff78b094e8e82fd5e78ef3a7edb157149abbff6"

      def install
        bin.install "oslatlong"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.1/oslatlong_0.0.1_Linux_x86_64.tar.gz"
      sha256 "4f42ec4982ac21e0a0da22543c0a23064c60b5c1e6bf1ad16eb146ca1a54aefd"

      def install
        bin.install "oslatlong"
      end
    end
  end
end
