# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oslatlong < Formula
  desc "OSM Nominatim skinny CLI"
  homepage "https://github.com/oogali/oslatlong"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.3/oslatlong_0.0.3_Darwin_arm64.tar.gz"
      sha256 "5bc6500d101a588962a47c1989d2d5f732ab2ed23f5163b6bdedebbc4f80ee6c"

      def install
        bin.install "oslatlong"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.3/oslatlong_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "156d71bd74f793138a34f3733783e2170d1f31b2ba265315b4f2c4f992394814"

      def install
        bin.install "oslatlong"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.3/oslatlong_0.0.3_Linux_arm64.tar.gz"
      sha256 "ec1bb3c7732a88bed814daccbdf0584a1afd9107185f3b20fdbb40afd0d52386"

      def install
        bin.install "oslatlong"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.3/oslatlong_0.0.3_Linux_x86_64.tar.gz"
      sha256 "c2bf8b31528c87e4e74361adcfd5f36509530db502fda489505eaf120d28c35e"

      def install
        bin.install "oslatlong"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/oogali/oslatlong/releases/download/v0.0.3/oslatlong_0.0.3_Linux_armv6.tar.gz"
      sha256 "b3c29972f0897151b75a9241fb270ea5c264c8a7f326c5a72c79592bcf997220"

      def install
        bin.install "oslatlong"
      end
    end
  end
end
